# Bussiness Problem- Predict the Sale Price of House 
Using Linear Regression- Supervised Machine Learning Algorithm

In [1]:
# Load Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Read dataset. Here the data is already preprocessed. So, everything is in numerical form.
data = pd.read_csv('Transformed_Housing_Data2.csv')

In [3]:
data.head()

Sale_Price  No of Bedrooms  No of Bathrooms  Flat Area (in Sqft)  \
0    221900.0               3             1.00               1180.0   
1    538000.0               3             2.25               2570.0   
2    180000.0               2             1.00                770.0   
3    604000.0               4             3.00               1960.0   
4    510000.0               3             2.00               1680.0   

   Lot Area (in Sqft)  No of Floors  No of Times Visited  Overall Grade  \
0              5650.0           1.0                    0              7   
1              7242.0           2.0                    0              7   
2             10000.0           1.0                    0              6   
3              5000.0           1.0                    0              7   
4              8080.0           1.0                    0              8   

   Area of the House from Basement (in Sqft)  Basement Area (in Sqft)  ...  \
0                                     1180.0                        0  ...   
1                                     2170.0                      400  ...   
2                                      770.0                        0  ...   
3                                     1050.0                      910  ...   
4                                     1680.0                        0  ...   

   Waterfront_View_Yes  Zipcode_Group_Zipcode_Group_1  \
0                    0                              0   
1                    0                              0   
2                    0                              0   
3                    0                              0   
4                    0                              0   

   Zipcode_Group_Zipcode_Group_2  Zipcode_Group_Zipcode_Group_3  \
0                              0                              0   
1                              1                              0   
2                              1                              0   
3                              0                              1   
4                              0                              0   

   Zipcode_Group_Zipcode_Group_4  Zipcode_Group_Zipcode_Group_5  \
0                              0                              0   
1                              0                              0   
2                              0                              0   
3                              0                              0   
4                              1                              0   

   Zipcode_Group_Zipcode_Group_6  Zipcode_Group_Zipcode_Group_7  \
0                              0                              0   
1                              0                              0   
2                              0                              0   
3                              0                              0   
4                              0                              0   

   Zipcode_Group_Zipcode_Group_8  Zipcode_Group_Zipcode_Group_9  
0                              0                              0  
1                              0                              0  
2                              0                              0  
3                              0                              0  
4                              0                              0  

[5 rows x 31 columns]

In [5]:
# Split the data into x and y
x=data.drop('Sale_Price', axis=1)  # Every feature will be present in x except Sale Price
y=data['Sale_Price']               # y is the dependent variable

print("Shape of x= ",x.shape)
print("Shape of y= ",y.shape)

Shape of x=  (21609, 30)
Shape of y=  (21609,)


In [6]:
# Here we split in train and test and the test percentage is 20%
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.20,random_state =2)

print("Shape of x_train= ",x_train.shape)
print("Shape of y_train= ",y_train.shape)
print("Shape of x_test= ",x_test.shape)
print("Shape of y_test= ",y_test.shape)

Shape of x_train=  (17287, 30)
Shape of y_train=  (17287,)
Shape of x_test=  (4322, 30)
Shape of y_test=  (4322,)


In [7]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train=sc.transform(x_train)
x_test=sc.transform(x_test)

In [9]:
# Linear Regression ML Model Training
from sklearn.linear_model import LinearRegression
lr = LinearRegression()                           # Here, lr is the object of Linear regression 

lr.fit(x_train,y_train)

LinearRegression()

In [11]:
lr.coef_

array([ -5369.84434613,  11296.92766554,  99009.53967833,  12357.18094644,
         2307.43064784,  26765.12514037,  59266.22209073,  -8548.61212834,
       -19190.96386439,  27588.90227405,  21663.73597741, -23298.70747776,
        18992.5799921 ,  -1692.79684653, -10854.48798666,  32627.79734713,
        33402.86413715,  35779.07026657,   4728.22241415,  14593.11393793,
         8984.02861075,  12801.49772744,  33802.64179801,  61407.55774243,
        81442.84382197,  51351.55163861,  72871.40571863,  40707.39606058,
        68109.52161162,  19104.1713556 ])

In [12]:
lr.intercept_

511518.794180599

In [13]:
# Predict the value of Home and Test
x_test[0, :]

array([ 0.67075316,  0.50022204,  0.14122811, -0.19272645,  0.9317619 ,
       -0.30463735,  0.33911938,  0.50705076, -0.65653352, -0.74864987,
       -1.00511819,  0.21658224, -0.02702678, -0.20930511, -0.16896802,
       -0.29419269,  0.7340373 , -0.59349572, -0.09292619, -0.21132431,
       -0.08805279, -0.35087876, -0.48163242, -0.41798062, -0.48190583,
       -0.21296207, -0.2871709 , -0.11301191, -0.16863317, -0.04439225])

In [14]:
lr.predict([x_test[0, :]])

array([356616.17424022])

In [15]:
lr.predict(x_test)

array([356616.17424022, 466455.66208663, 342991.27126532, ...,
       404018.40035346, 523491.22185987, 854546.82624282])

In [16]:
y_test

12179    382500.0
13559    500000.0
8370     435000.0
9208     350000.0
11439    827500.0
           ...   
19141    635500.0
13519    585000.0
20501    355000.0
1080     515000.0
15818    784000.0
Name: Sale_Price, Length: 4322, dtype: float64

In [18]:
lr.score(x_test, y_test)*100

84.43695273016894