In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('Transformed_Housing_Data2.csv')

In [3]:
data.head()

Sale_Price  No of Bedrooms  No of Bathrooms  Flat Area (in Sqft)  \
0    221900.0               3             1.00               1180.0   
1    538000.0               3             2.25               2570.0   
2    180000.0               2             1.00                770.0   
3    604000.0               4             3.00               1960.0   
4    510000.0               3             2.00               1680.0   

   Lot Area (in Sqft)  No of Floors  No of Times Visited  Overall Grade  \
0              5650.0           1.0                    0              7   
1              7242.0           2.0                    0              7   
2             10000.0           1.0                    0              6   
3              5000.0           1.0                    0              7   
4              8080.0           1.0                    0              8   

   Area of the House from Basement (in Sqft)  Basement Area (in Sqft)  ...  \
0                                     1180.0                        0  ...   
1                                     2170.0                      400  ...   
2                                      770.0                        0  ...   
3                                     1050.0                      910  ...   
4                                     1680.0                        0  ...   

   Waterfront_View_Yes  Zipcode_Group_Zipcode_Group_1  \
0                    0                              0   
1                    0                              0   
2                    0                              0   
3                    0                              0   
4                    0                              0   

   Zipcode_Group_Zipcode_Group_2  Zipcode_Group_Zipcode_Group_3  \
0                              0                              0   
1                              1                              0   
2                              1                              0   
3                              0                              1   
4                              0                              0   

   Zipcode_Group_Zipcode_Group_4  Zipcode_Group_Zipcode_Group_5  \
0                              0                              0   
1                              0                              0   
2                              0                              0   
3                              0                              0   
4                              1                              0   

   Zipcode_Group_Zipcode_Group_6  Zipcode_Group_Zipcode_Group_7  \
0                              0                              0   
1                              0                              0   
2                              0                              0   
3                              0                              0   
4                              0                              0   

   Zipcode_Group_Zipcode_Group_8  Zipcode_Group_Zipcode_Group_9  
0                              0                              0  
1                              0                              0  
2                              0                              0  
3                              0                              0  
4                              0                              0  

[5 rows x 31 columns]

In [4]:
data.describe()

Sale_Price  No of Bedrooms  No of Bathrooms  Flat Area (in Sqft)  \
count  2.160900e+04    21609.000000     21609.000000         21609.000000   
mean   5.116186e+05        3.370771         2.114709          2079.872553   
std    2.500620e+05        0.929916         0.770097           918.347816   
min    7.500000e+04        0.000000         0.000000           290.000000   
25%    3.219500e+05        3.000000         1.750000          1430.000000   
50%    4.500000e+05        3.000000         2.250000          1910.000000   
75%    6.450000e+05        4.000000         2.500000          2550.000000   
max    1.129575e+06       33.000000         8.000000         13540.000000   

       Lot Area (in Sqft)  No of Floors  No of Times Visited  Overall Grade  \
count        2.160900e+04  21609.000000         21609.000000   21609.000000   
mean         1.510641e+04      1.494215             0.234347       7.623490   
std          4.142353e+04      0.539909             0.766382       1.105519   
min          5.200000e+02      1.000000             0.000000       1.000000   
25%          5.040000e+03      1.000000             0.000000       7.000000   
50%          7.619000e+03      1.500000             0.000000       7.000000   
75%          1.068700e+04      2.000000             0.000000       8.000000   
max          1.651359e+06      3.500000             4.000000      10.000000   

       Area of the House from Basement (in Sqft)  Basement Area (in Sqft)  \
count                               21609.000000             21609.000000   
mean                                 1788.319589               291.513490   
std                                   827.977604               442.570991   
min                                   290.000000                 0.000000   
25%                                  1190.000000                 0.000000   
50%                                  1560.000000                 0.000000   
75%                                  2210.000000               560.000000   
max                                  9410.000000              4820.000000   

       ...  Waterfront_View_Yes  Zipcode_Group_Zipcode_Group_1  \
count  ...         21609.000000                   21609.000000   
mean   ...             0.007543                       0.109399   
std    ...             0.086525                       0.312146   
min    ...             0.000000                       0.000000   
25%    ...             0.000000                       0.000000   
50%    ...             0.000000                       0.000000   
75%    ...             0.000000                       0.000000   
max    ...             1.000000                       1.000000   

       Zipcode_Group_Zipcode_Group_2  Zipcode_Group_Zipcode_Group_3  \
count                   21609.000000                   21609.000000   
mean                        0.188625                       0.149706   
std                         0.391220                       0.356791   
min                         0.000000                       0.000000   
25%                         0.000000                       0.000000   
50%                         0.000000                       0.000000   
75%                         0.000000                       0.000000   
max                         1.000000                       1.000000   

       Zipcode_Group_Zipcode_Group_4  Zipcode_Group_Zipcode_Group_5  \
count                   21609.000000                   21609.000000   
mean                        0.186681                       0.043824   
std                         0.389665                       0.204709   
min                         0.000000                       0.000000   
25%                         0.000000                       0.000000   
50%                         0.000000                       0.000000   
75%                         0.000000                       0.000000   
max                         1.000000                       1.000000   

       Zipcode_Group_Zipcode_Group

In [5]:
x=data.drop('Sale_Price', axis=1)
y=data['Sale_Price']

print("Shape of x= ",x.shape)
print("Shape of y= ",y.shape)

Shape of x=  (21609, 30)
Shape of y=  (21609,)


In [6]:
data.head()

Sale_Price  No of Bedrooms  No of Bathrooms  Flat Area (in Sqft)  \
0    221900.0               3             1.00               1180.0   
1    538000.0               3             2.25               2570.0   
2    180000.0               2             1.00                770.0   
3    604000.0               4             3.00               1960.0   
4    510000.0               3             2.00               1680.0   

   Lot Area (in Sqft)  No of Floors  No of Times Visited  Overall Grade  \
0              5650.0           1.0                    0              7   
1              7242.0           2.0                    0              7   
2             10000.0           1.0                    0              6   
3              5000.0           1.0                    0              7   
4              8080.0           1.0                    0              8   

   Area of the House from Basement (in Sqft)  Basement Area (in Sqft)  ...  \
0                                     1180.0                        0  ...   
1                                     2170.0                      400  ...   
2                                      770.0                        0  ...   
3                                     1050.0                      910  ...   
4                                     1680.0                        0  ...   

   Waterfront_View_Yes  Zipcode_Group_Zipcode_Group_1  \
0                    0                              0   
1                    0                              0   
2                    0                              0   
3                    0                              0   
4                    0                              0   

   Zipcode_Group_Zipcode_Group_2  Zipcode_Group_Zipcode_Group_3  \
0                              0                              0   
1                              1                              0   
2                              1                              0   
3                              0                              1   
4                              0                              0   

   Zipcode_Group_Zipcode_Group_4  Zipcode_Group_Zipcode_Group_5  \
0                              0                              0   
1                              0                              0   
2                              0                              0   
3                              0                              0   
4                              1                              0   

   Zipcode_Group_Zipcode_Group_6  Zipcode_Group_Zipcode_Group_7  \
0                              0                              0   
1                              0                              0   
2                              0                              0   
3                              0                              0   
4                              0                              0   

   Zipcode_Group_Zipcode_Group_8  Zipcode_Group_Zipcode_Group_9  
0                              0                              0  
1                              0                              0  
2                              0                              0  
3                              0                              0  
4                              0                              0  

[5 rows x 31 columns]

In [7]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.10,random_state =2)

print("Shape of x_train= ",x_train.shape)
print("Shape of y_train= ",y_train.shape)
print("Shape of x_test= ",x_test.shape)
print("Shape of y_test= ",y_test.shape)

Shape of x_train=  (19448, 30)
Shape of y_train=  (19448,)
Shape of x_test=  (2161, 30)
Shape of y_test=  (2161,)


In [8]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train=sc.transform(x_train)
x_test=sc.transform(x_test)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21609 entries, 0 to 21608
Data columns (total 31 columns):
 #   Column                                     Non-Null Count  Dtype  
---  ------                                     --------------  -----  
 0   Sale_Price                                 21609 non-null  float64
 1   No of Bedrooms                             21609 non-null  int64  
 2   No of Bathrooms                            21609 non-null  float64
 3   Flat Area (in Sqft)                        21609 non-null  float64
 4   Lot Area (in Sqft)                         21609 non-null  float64
 5   No of Floors                               21609 non-null  float64
 6   No of Times Visited                        21609 non-null  int64  
 7   Overall Grade                              21609 non-null  int64  
 8   Area of the House from Basement (in Sqft)  21609 non-null  float64
 9   Basement Area (in Sqft)                    21609 non-null  int64  
 10  Age of House (in Years

In [10]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

lr.fit(x_train,y_train)

LinearRegression()

In [11]:
lr.coef_

array([ -5009.0467778 ,  12442.87502946,  99635.1942213 ,  12480.73130747,
         2140.98582024,  27168.97305965,  58157.60920131,  -8002.04782007,
       -19742.54002394,  27647.35214522,  21578.47184653, -23918.60499658,
        18862.40145267,  -1732.05113019, -10874.98010271,  31513.59801875,
        31729.53056791,  34394.7228637 ,   4196.79942047,  14756.25586944,
         8708.57174939,  12573.47768295,  33908.27283293,  62162.30453954,
        80757.1276861 ,  50770.81310166,  73080.16248716,  40472.03291337,
        68681.76481645,  19762.05431714])

In [12]:
lr.intercept_

511277.3575689002

In [14]:
x_test[0, :]

array([ 0.67552362,  0.50182865,  0.14218627, -0.19521067,  0.93350472,
       -0.30487876,  0.33970382,  0.5097103 , -0.65733797, -0.74959662,
       -1.00603487,  0.21713694, -0.02413174, -0.21091747, -0.16742219,
       -0.29324919,  0.73315268, -0.5938991 , -0.09107861, -0.21034255,
       -0.08636894, -0.35236607, -0.48147859, -0.41905009, -0.47880294,
       -0.21325801, -0.28720924, -0.1127195 , -0.16979812, -0.04596346])

In [15]:
lr.predict([x_test[0, :]])

array([357277.54088882])

In [16]:
lr.predict(x_test)

array([357277.54088882, 463297.96196629, 345127.55955056, ...,
       283608.08987848, 610734.7209454 , 690135.62105178])

In [17]:
y_test

12179     382500.0
13559     500000.0
8370      435000.0
9208      350000.0
11439     827500.0
           ...    
19667     299900.0
1486      514000.0
8698      330000.0
4225      755000.0
21177    1050000.0
Name: Sale_Price, Length: 2161, dtype: float64

In [18]:
lr.score(x_test, y_test)

0.8490532126908343